# Generated by Django 4.2.20 on 2025-03-25 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('REP', 'Repair'), ('INST', 'Installation'), ('BILL', 'Billing'), ('SAFE', 'Safety Inspection')], max_length=4)),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('PRO', 'In Progress'), ('RES', 'Resolved')], default='PEN', max_length=3)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HIGH', 'High')], default='MED', max_length=4)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='request_attachments/')),
                ('comments', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
